# Generated by Django 5.0.2 on 2024-03-03 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='course_previews/', verbose_name='preview')),
                ('description', models.TextField(verbose_name='description')),
                ('url', models.URLField(blank=True, null=True, verbose_name='url')),
                ('price', models.PositiveIntegerField(null=True, verbose_name='price')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='lesson_previews/', verbose_name='preview')),
                ('description', models.TextField(verbose_name='description')),
                ('url', models.URLField(blank=True, null=True, verbose_name='url')),
            ],
            options={
                'verbose_name': 'lesson',
                'verbose_name_plural': 'lessons',
            },
        ),
        migrations.CreateModel(
            name='CoursePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_amount', models.CharField(blank=True, null=True, verbose_name='payment_price')),
                ('payment_link', models.URLField(blank=True, max_length=400, null=True, verbose_name='link_to_payment')),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='id_of_payment')),
                ('name', models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.course', verbose_name='name_of_product')),
            ],
            options={
                'verbose_name': 'course payment',
                'verbose_name_plural': 'course payments',
            },
        ),
        migrations.CreateModel(
            name='CourseSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.course')),
            ],
        ),
    ]
