# Generated by Django 3.2.25 on 2024-03-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_alter_coursesubscription_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepayment',
            name='price_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='payment_price'),
        ),
    ]
