# Generated by Django 5.0.1 on 2024-02-17 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0010_coursesubscription_valid_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesubscription',
            name='valid_subscription',
        ),
    ]
