# Generated by Django 5.0.1 on 2024-02-24 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0020_course_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_link', models.URLField(blank=True, max_length=400, null=True, verbose_name='link_to_payment')),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='id_of_payment')),
                ('price_amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.course', verbose_name='payment_price')),
            ],
            options={
                'verbose_name': 'course payment',
                'verbose_name_plural': 'course payments',
            },
        ),
    ]
