# Generated by Django 5.0.1 on 2024-02-27 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0022_alter_coursepayment_price_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepayment',
            name='price_amount',
        ),
        migrations.AddField(
            model_name='coursepayment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_payments', to='materials.course'),
        ),
    ]
