# Generated by Django 5.0.1 on 2024-02-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0023_remove_coursepayment_price_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepayment',
            name='course',
        ),
        migrations.AddField(
            model_name='coursepayment',
            name='price_amount',
            field=models.CharField(blank=True, null=True, verbose_name='payment_price'),
        ),
    ]
