# Generated by Django 5.0.1 on 2024-02-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_coursesubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesubscription',
            name='valid_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
