# Generated by Django 5.0.1 on 2024-02-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0019_alter_lesson_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(null=True, verbose_name='price'),
        ),
    ]
