# Generated by Django 5.0.1 on 2024-02-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0021_coursepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepayment',
            name='price_amount',
            field=models.CharField(verbose_name='payment_price'),
        ),
    ]
